[PHP]
memory_limit        = ${PHP_MEMORY_LIMIT}
upload_max_filesize = ${PHP_UPLOAD_MAX}
post_max_size       = ${PHP_POST_MAX}
max_execution_time  = ${PHP_MAX_EXEC}
date.timezone       = UTC

[opcache]
opcache.enable                  = 1
opcache.memory_consumption      = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files   = 4000
opcache.revalidate_freq         = 2
opcache.fast_shutdown           = 1
