<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260621125545 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add audit trail tables (book_audit, user_audit, category_audit, library_request_audit) for damienharper/auditor-bundle.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE book_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_0be92e2dd46c870bfb3282bf70b0077c_idx ON book_audit (type)');
        $this->addSql('CREATE INDEX object_id_0be92e2dd46c870bfb3282bf70b0077c_idx ON book_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_0be92e2dd46c870bfb3282bf70b0077c_idx ON book_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_0be92e2dd46c870bfb3282bf70b0077c_idx ON book_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_0be92e2dd46c870bfb3282bf70b0077c_idx ON book_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_0be92e2dd46c870bfb3282bf70b0077c_idx ON book_audit (created_at)');
        $this->addSql('CREATE TABLE category_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_9d60be1ae31861a527fd590d589be976_idx ON category_audit (type)');
        $this->addSql('CREATE INDEX object_id_9d60be1ae31861a527fd590d589be976_idx ON category_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_9d60be1ae31861a527fd590d589be976_idx ON category_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_9d60be1ae31861a527fd590d589be976_idx ON category_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_9d60be1ae31861a527fd590d589be976_idx ON category_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_9d60be1ae31861a527fd590d589be976_idx ON category_audit (created_at)');
        $this->addSql('CREATE TABLE library_request_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_9ccb61376d4f35efd7bd75618f556c98_idx ON library_request_audit (type)');
        $this->addSql('CREATE INDEX object_id_9ccb61376d4f35efd7bd75618f556c98_idx ON library_request_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_9ccb61376d4f35efd7bd75618f556c98_idx ON library_request_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_9ccb61376d4f35efd7bd75618f556c98_idx ON library_request_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_9ccb61376d4f35efd7bd75618f556c98_idx ON library_request_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_9ccb61376d4f35efd7bd75618f556c98_idx ON library_request_audit (created_at)');
        $this->addSql('CREATE TABLE user_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_e06395edc291d0719bee26fd39a32e8a_idx ON user_audit (type)');
        $this->addSql('CREATE INDEX object_id_e06395edc291d0719bee26fd39a32e8a_idx ON user_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_e06395edc291d0719bee26fd39a32e8a_idx ON user_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_e06395edc291d0719bee26fd39a32e8a_idx ON user_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_e06395edc291d0719bee26fd39a32e8a_idx ON user_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_e06395edc291d0719bee26fd39a32e8a_idx ON user_audit (created_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE book_audit');
        $this->addSql('DROP TABLE category_audit');
        $this->addSql('DROP TABLE library_request_audit');
        $this->addSql('DROP TABLE user_audit');
    }
}
