<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The Messenger Doctrine transport's queue table, backing outbound mail.
 *
 * The transport can create this itself (`auto_setup`), but that would mean a
 * worker booting into DDL against the production database on first send — and
 * a table whose shape lives nowhere in the repo. The DSNs therefore carry
 * `auto_setup=0` and the schema is checked in here instead; it is a verbatim
 * dump of `Connection::configureSchema()` for the PostgreSQL platform, so the
 * transport finds exactly what it expects.
 *
 * No LISTEN/NOTIFY trigger: the transport issues its own `SELECT pg_notify(...)`
 * on send (Connection::send), so the worker still wakes immediately.
 *
 * The table is NOT part of the ORM mapping, so `migrations:diff` neither
 * generates nor drops it — and it is not on the audit whitelist (auditing a
 * queue would double every write to log a row that deletes itself).
 */
final class Version20260831090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add the messenger_messages queue table (async mail delivery)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        // One composite index, in the order the transport's own SELECT ... FOR
        // UPDATE SKIP LOCKED filters and sorts. Its name is the transport's, not
        // ours: keep it verbatim so auto_setup would consider the table current.
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');
    }
}
