<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Record the full borrow-request lifecycle:
 *  - new library_request_event table — an immutable, ordered audit trail so each
 *    step (requested → approved/declined → return requested → returned) is kept,
 *    not just the request's final status.
 *  - book.current_holder_id — who physically holds each book right now (owner
 *    while home, borrower while lent), so availability is a direct lookup.
 *
 * Existing rows are backfilled: every book's holder is seeded (owner, or the
 * active borrower for live loans) and events are reconstructed from the
 * timestamps already stored on each request (best-effort for historical data).
 */
final class Version20260621105713 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add library_request_event audit trail and book.current_holder';
    }

    public function up(Schema $schema): void
    {
        // ── Lifecycle event audit trail ──────────────────────────────────────
        $this->addSql('CREATE TABLE library_request_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, request_id INT NOT NULL, actor_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D5E3961F427EB8A5 ON library_request_event (request_id)');
        $this->addSql('CREATE INDEX IDX_D5E3961F10DAF24A ON library_request_event (actor_id)');
        $this->addSql('ALTER TABLE library_request_event ADD CONSTRAINT FK_D5E3961F427EB8A5 FOREIGN KEY (request_id) REFERENCES library_request (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE library_request_event ADD CONSTRAINT FK_D5E3961F10DAF24A FOREIGN KEY (actor_id) REFERENCES "user" (id) NOT DEFERRABLE');

        // ── book.current_holder: add nullable, backfill, then enforce NOT NULL ─
        $this->addSql('ALTER TABLE book ADD current_holder_id INT DEFAULT NULL');
        // Every book starts held by its owner…
        $this->addSql('UPDATE book SET current_holder_id = owner_id');
        // …except books out on an active loan, held by the borrower.
        $this->addSql(<<<'SQL'
            UPDATE book b
            SET current_holder_id = lr.requester_id
            FROM library_request lr
            WHERE lr.book_id = b.id
              AND lr.status IN ('approved', 'return_pending')
        SQL);
        $this->addSql('ALTER TABLE book ALTER current_holder_id SET NOT NULL');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT FK_CBE5A3315C8D37C FOREIGN KEY (current_holder_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_CBE5A3315C8D37C ON book (current_holder_id)');

        // ── Reconstruct events for pre-existing requests from stored timestamps ─
        // Every request began with a borrow request by the requester.
        $this->addSql(<<<'SQL'
            INSERT INTO library_request_event (type, actor_id, due_date, created_at, request_id)
            SELECT 'requested', lr.requester_id, NULL, lr.requested_at, lr.id
            FROM library_request lr
        SQL);
        // Loans that were approved (still active or since returned).
        // library_request.due_date is introduced in a later migration
        // (Version20260621130000), so no historical row can carry one here — the
        // event due_date is left NULL for backfilled approvals.
        $this->addSql(<<<'SQL'
            INSERT INTO library_request_event (type, actor_id, due_date, created_at, request_id)
            SELECT 'approved', b.owner_id, NULL, lr.resolved_at, lr.id
            FROM library_request lr
            JOIN book b ON b.id = lr.book_id
            WHERE lr.status IN ('approved', 'return_pending', 'returned')
              AND lr.resolved_at IS NOT NULL
        SQL);
        // Requests the owner declined.
        $this->addSql(<<<'SQL'
            INSERT INTO library_request_event (type, actor_id, due_date, created_at, request_id)
            SELECT 'declined', b.owner_id, NULL, lr.resolved_at, lr.id
            FROM library_request lr
            JOIN book b ON b.id = lr.book_id
            WHERE lr.status = 'declined'
              AND lr.resolved_at IS NOT NULL
        SQL);
        // Loans the owner confirmed returned. (The intermediate "return requested"
        // step has no stored timestamp for historical rows, so it is omitted.)
        // library_request.returned_at is introduced in a later migration
        // (Version20260621130000); resolved_at is the closest timestamp available
        // for historical rows at this point.
        $this->addSql(<<<'SQL'
            INSERT INTO library_request_event (type, actor_id, due_date, created_at, request_id)
            SELECT 'returned', b.owner_id, NULL, lr.resolved_at, lr.id
            FROM library_request lr
            JOIN book b ON b.id = lr.book_id
            WHERE lr.status = 'returned'
              AND lr.resolved_at IS NOT NULL
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE library_request_event DROP CONSTRAINT FK_D5E3961F427EB8A5');
        $this->addSql('ALTER TABLE library_request_event DROP CONSTRAINT FK_D5E3961F10DAF24A');
        $this->addSql('DROP TABLE library_request_event');
        $this->addSql('ALTER TABLE book DROP CONSTRAINT FK_CBE5A3315C8D37C');
        $this->addSql('DROP INDEX IDX_CBE5A3315C8D37C');
        $this->addSql('ALTER TABLE book DROP current_holder_id');
    }
}
