<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260711120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add book collections: book_collection (+ join, audit), collection_request (+ audit), and library_request.parent_request_id linking child loans to their parent collection request.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE book_collection (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(500) DEFAULT NULL, cover_url VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_63E02F817E3C61F9 ON book_collection (owner_id)');
        $this->addSql('CREATE TABLE book_collection_book (book_collection_id INT NOT NULL, book_id INT NOT NULL, PRIMARY KEY (book_collection_id, book_id))');
        $this->addSql('CREATE INDEX IDX_5251DA434A06EF1 ON book_collection_book (book_collection_id)');
        $this->addSql('CREATE INDEX IDX_5251DA416A2B381 ON book_collection_book (book_id)');
        $this->addSql('CREATE TABLE book_collection_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_7e7599e3c228c363112d1dbfd0c91ef3_idx ON book_collection_audit (type)');
        $this->addSql('CREATE INDEX object_id_7e7599e3c228c363112d1dbfd0c91ef3_idx ON book_collection_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_7e7599e3c228c363112d1dbfd0c91ef3_idx ON book_collection_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_7e7599e3c228c363112d1dbfd0c91ef3_idx ON book_collection_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_7e7599e3c228c363112d1dbfd0c91ef3_idx ON book_collection_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_7e7599e3c228c363112d1dbfd0c91ef3_idx ON book_collection_audit (created_at)');
        $this->addSql('CREATE TABLE collection_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, returned_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, decline_message VARCHAR(255) DEFAULT NULL, collection_id INT NOT NULL, requester_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6FBBFD4E514956FD ON collection_request (collection_id)');
        $this->addSql('CREATE INDEX IDX_6FBBFD4EED442CF4 ON collection_request (requester_id)');
        $this->addSql('CREATE TABLE collection_request_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_ba6e232a50d103bf21ace525c6b06b1b_idx ON collection_request_audit (type)');
        $this->addSql('CREATE INDEX object_id_ba6e232a50d103bf21ace525c6b06b1b_idx ON collection_request_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_ba6e232a50d103bf21ace525c6b06b1b_idx ON collection_request_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_ba6e232a50d103bf21ace525c6b06b1b_idx ON collection_request_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_ba6e232a50d103bf21ace525c6b06b1b_idx ON collection_request_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_ba6e232a50d103bf21ace525c6b06b1b_idx ON collection_request_audit (created_at)');
        $this->addSql('ALTER TABLE book_collection ADD CONSTRAINT FK_63E02F817E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE book_collection_book ADD CONSTRAINT FK_5251DA434A06EF1 FOREIGN KEY (book_collection_id) REFERENCES book_collection (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE book_collection_book ADD CONSTRAINT FK_5251DA416A2B381 FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE collection_request ADD CONSTRAINT FK_6FBBFD4E514956FD FOREIGN KEY (collection_id) REFERENCES book_collection (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE collection_request ADD CONSTRAINT FK_6FBBFD4EED442CF4 FOREIGN KEY (requester_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE library_request ADD parent_request_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE library_request ADD CONSTRAINT FK_415637AF53D3CF5 FOREIGN KEY (parent_request_id) REFERENCES collection_request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_415637AF53D3CF5 ON library_request (parent_request_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE book_collection DROP CONSTRAINT FK_63E02F817E3C61F9');
        $this->addSql('ALTER TABLE book_collection_book DROP CONSTRAINT FK_5251DA434A06EF1');
        $this->addSql('ALTER TABLE book_collection_book DROP CONSTRAINT FK_5251DA416A2B381');
        $this->addSql('ALTER TABLE collection_request DROP CONSTRAINT FK_6FBBFD4E514956FD');
        $this->addSql('ALTER TABLE collection_request DROP CONSTRAINT FK_6FBBFD4EED442CF4');
        $this->addSql('DROP TABLE book_collection');
        $this->addSql('DROP TABLE book_collection_book');
        $this->addSql('DROP TABLE book_collection_audit');
        $this->addSql('DROP TABLE collection_request');
        $this->addSql('DROP TABLE collection_request_audit');
        $this->addSql('ALTER TABLE library_request DROP CONSTRAINT FK_415637AF53D3CF5');
        $this->addSql('DROP INDEX IDX_415637AF53D3CF5');
        $this->addSql('ALTER TABLE library_request DROP parent_request_id');
    }
}
