<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260621160739 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add user_settings table holding per-user privacy and notification preferences (1:1 with user).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, allow_requests BOOLEAN DEFAULT true NOT NULL, show_location BOOLEAN DEFAULT true NOT NULL, notify_borrow_requests BOOLEAN DEFAULT true NOT NULL, notify_request_updates BOOLEAN DEFAULT true NOT NULL, notify_activity BOOLEAN DEFAULT false NOT NULL, notify_newsletter BOOLEAN DEFAULT false NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C844C5A76ED395 ON user_settings (user_id)');
        $this->addSql('ALTER TABLE user_settings ADD CONSTRAINT FK_5C844C5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_settings DROP CONSTRAINT FK_5C844C5A76ED395');
        $this->addSql('DROP TABLE user_settings');
    }
}
