<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260621193042 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add subscription table (follow edges) + its audit companion.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, subscriber_id INT NOT NULL, subscribed_to_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A3C664D3F9B6176 ON subscription (subscribed_to_id)');
        $this->addSql('CREATE INDEX idx_subscription_subscriber ON subscription (subscriber_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_subscription_pair ON subscription (subscriber_id, subscribed_to_id)');
        $this->addSql('CREATE TABLE subscription_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_27ba2abfb6376bca6f1db18880bc4ede_idx ON subscription_audit (type)');
        $this->addSql('CREATE INDEX object_id_27ba2abfb6376bca6f1db18880bc4ede_idx ON subscription_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_27ba2abfb6376bca6f1db18880bc4ede_idx ON subscription_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_27ba2abfb6376bca6f1db18880bc4ede_idx ON subscription_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_27ba2abfb6376bca6f1db18880bc4ede_idx ON subscription_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_27ba2abfb6376bca6f1db18880bc4ede_idx ON subscription_audit (created_at)');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D37808B1AD FOREIGN KEY (subscriber_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3F9B6176 FOREIGN KEY (subscribed_to_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE subscription DROP CONSTRAINT FK_A3C664D37808B1AD');
        $this->addSql('ALTER TABLE subscription DROP CONSTRAINT FK_A3C664D3F9B6176');
        $this->addSql('DROP TABLE subscription');
        $this->addSql('DROP TABLE subscription_audit');
    }
}
