<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Adds the two analytics counter tables behind the operator dashboard's traffic
 * section.
 *
 * page_view_daily is one row per (route, day) with a hit counter. `route` holds
 * an SPA route *name*, never a URL path — paths carry ids, which would give the
 * table a row per profile per day and turn "top pages" into a list of people.
 * `day` is a real DATE so the dashboard can group on it in plain DQL.
 *
 * page_view_visitor is one row per (day, distinct visitor). Exact daily-unique
 * counting has to remember whom it already counted today, so this is the minimum
 * state — it is still not per-visit. The hash is salted with the day itself, so
 * it identifies nobody across days, and `app:prune-analytics` deletes rows past
 * 120 days. page_view_daily is never pruned; it grows a few thousand rows a year.
 *
 * Neither table goes on the auditor whitelist: they are append-and-increment
 * counters, the same reason ActivityItem and LibraryRequestEvent are excluded.
 */
final class Version20260811203022 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add page_view_daily and page_view_visitor analytics counters';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE page_view_daily (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, route VARCHAR(64) NOT NULL, day DATE NOT NULL, views INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_page_view_daily_route_day ON page_view_daily (route, day)');
        // `day` is the trailing column of the unique index above, so it needs its
        // own index for the window queries that filter on it alone.
        $this->addSql('CREATE INDEX idx_page_view_daily_day ON page_view_daily (day)');

        $this->addSql('CREATE TABLE page_view_visitor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day DATE NOT NULL, visitor_hash VARCHAR(32) NOT NULL, authenticated BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY (id))');
        // `day` leads this one, so the range scans reuse it — no second index.
        $this->addSql('CREATE UNIQUE INDEX uniq_page_view_visitor_day_hash ON page_view_visitor (day, visitor_hash)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE page_view_daily');
        $this->addSql('DROP TABLE page_view_visitor');
    }
}
