<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The record of letters sent from the Intercom tab.
 *
 * Hand-trimmed like every migration here: diff also emitted DROP INDEX for each
 * partial index (it cannot see their WHERE clauses, so it reads them as drift)
 * plus the two phantom `user` statements. Only the table is real.
 *
 * `sent_by_id` is ON DELETE SET NULL so an anonymized operator does not take the
 * record of what they sent with them — the same rule ActivityItem's target
 * follows, and the reason UserPurger anonymizes rather than deleting.
 */
final class Version20260906200228 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add intercom_letter';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE intercom_letter (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, subject VARCHAR(120) NOT NULL, intro TEXT DEFAULT NULL, items JSON NOT NULL, recipient_count INT NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sent_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D092FF61A45BB98C ON intercom_letter (sent_by_id)');
        $this->addSql('ALTER TABLE intercom_letter ADD CONSTRAINT FK_D092FF61A45BB98C FOREIGN KEY (sent_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE intercom_letter DROP CONSTRAINT FK_D092FF61A45BB98C');
        $this->addSql('DROP TABLE intercom_letter');
    }
}
