<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260620203249 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action_type VARCHAR(255) NOT NULL, comment_text TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actor_id INT NOT NULL, target_book_id INT DEFAULT NULL, target_user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1CDFFE8C10DAF24A ON activity_item (actor_id)');
        $this->addSql('CREATE INDEX IDX_1CDFFE8CDDCA0AEA ON activity_item (target_book_id)');
        $this->addSql('CREATE INDEX IDX_1CDFFE8C6C066AFE ON activity_item (target_user_id)');
        $this->addSql('CREATE TABLE book (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, author VARCHAR(255) NOT NULL, isbn VARCHAR(32) DEFAULT NULL, cover_path VARCHAR(500) DEFAULT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CBE5A3317E3C61F9 ON book (owner_id)');
        $this->addSql('CREATE TABLE book_category (book_id INT NOT NULL, category_id INT NOT NULL, PRIMARY KEY (book_id, category_id))');
        $this->addSql('CREATE INDEX IDX_1FB30F9816A2B381 ON book_category (book_id)');
        $this->addSql('CREATE INDEX IDX_1FB30F9812469DE2 ON book_category (category_id)');
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, color_hex VARCHAR(7) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64C19C15E237E06 ON category (name)');
        $this->addSql('CREATE TABLE library_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, book_id INT NOT NULL, requester_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_415637AF16A2B381 ON library_request (book_id)');
        $this->addSql('CREATE INDEX IDX_415637AFED442CF4 ON library_request (requester_id)');
        $this->addSql('ALTER TABLE activity_item ADD CONSTRAINT FK_1CDFFE8C10DAF24A FOREIGN KEY (actor_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_item ADD CONSTRAINT FK_1CDFFE8CDDCA0AEA FOREIGN KEY (target_book_id) REFERENCES book (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_item ADD CONSTRAINT FK_1CDFFE8C6C066AFE FOREIGN KEY (target_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT FK_CBE5A3317E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE book_category ADD CONSTRAINT FK_1FB30F9816A2B381 FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE book_category ADD CONSTRAINT FK_1FB30F9812469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE library_request ADD CONSTRAINT FK_415637AF16A2B381 FOREIGN KEY (book_id) REFERENCES book (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE library_request ADD CONSTRAINT FK_415637AFED442CF4 FOREIGN KEY (requester_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD bio VARCHAR(300) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD location VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER INDEX uniq_user_google_id RENAME TO UNIQ_8D93D64976F5C865');
        $this->addSql('ALTER INDEX uniq_user_email RENAME TO UNIQ_8D93D649E7927C74');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity_item DROP CONSTRAINT FK_1CDFFE8C10DAF24A');
        $this->addSql('ALTER TABLE activity_item DROP CONSTRAINT FK_1CDFFE8CDDCA0AEA');
        $this->addSql('ALTER TABLE activity_item DROP CONSTRAINT FK_1CDFFE8C6C066AFE');
        $this->addSql('ALTER TABLE book DROP CONSTRAINT FK_CBE5A3317E3C61F9');
        $this->addSql('ALTER TABLE book_category DROP CONSTRAINT FK_1FB30F9816A2B381');
        $this->addSql('ALTER TABLE book_category DROP CONSTRAINT FK_1FB30F9812469DE2');
        $this->addSql('ALTER TABLE library_request DROP CONSTRAINT FK_415637AF16A2B381');
        $this->addSql('ALTER TABLE library_request DROP CONSTRAINT FK_415637AFED442CF4');
        $this->addSql('DROP TABLE activity_item');
        $this->addSql('DROP TABLE book');
        $this->addSql('DROP TABLE book_category');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE library_request');
        $this->addSql('ALTER TABLE "user" DROP bio');
        $this->addSql('ALTER TABLE "user" DROP location');
        $this->addSql('ALTER INDEX uniq_8d93d64976f5c865 RENAME TO uniq_user_google_id');
        $this->addSql('ALTER INDEX uniq_8d93d649e7927c74 RENAME TO uniq_user_email');
    }
}
